export default [
    {
        photo: "https://loremflickr.com/320/240/paris,girl/all",
        name: "Naam Bata",
        roll: 123456,
        branch: "Electrical Engineering",
        batch: "2K19",
        company: "Alpha",
    },
    {
        photo: "https://img.freepik.com/free-photo/close-up-young-successful-man-smiling-camera-standing-casual-outfit-against-blue-background_1258-66609.jpg?size=626&ext=jpg",
        name: "Naam Bata",
        roll: 123457,
        branch: "Electrical Engineering",
        batch: "2K19",
        company: "Beta",
    },
    {
        photo: "https://d3nn873nee648n.cloudfront.net/900x600/19305/220-SM915514.jpg",
        name: "Naam Bata",
        roll: 123458,
        branch: "Electrical Engineering",
        batch: "2K19",
        company: "Gama",
    },
    {
        photo: "https://picsum.photos/200",
        name: "Naam Bata",
        roll: 123459,
        branch: "Electrical Engineering",
        batch: "2K19",
        company: "Alpha",
    },
    {
        photo: "https://img.freepik.com/free-photo/cheerful-indian-businessman-smiling-closeup-portrait-jobs-career-campaign_53876-129417.jpg?size=626&ext=jpg",
        name: "Naam Bata",
        roll: 123460,
        branch: "Electrical Engineering",
        batch: "2K19",
        company: "Beta",
    },
    {
        photo: "https://picsum.photos/200/300",
        name: "Naam Bata",
        roll: 123461,
        branch: "Electrical Engineering",
        batch: "2K19",
        company: "Gama",
    },
];
